version: "3.9"

services:
  gdpr_app:
    build: .
    container_name: gdpr_app
    volumes:

      - ./data:/data
    environment:
      - DATABASE_PATH=/data/users.db
    stdin_open: true
    tty: true

