version: "3.9"

services:
  gdpr_app:
    build: .
    container_name: gdpr_app
    volumes:
      - ./data:/app  # Persistens f√∂r SQLite-databasen
    environment:
      - DATABASE_PATH=/app/users.db
